# Generated by Django 5.2.5 on 2025-08-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('mini_title', models.CharField(max_length=100)),
                ('max_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='home/')),
                ('about_title', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
                ('about_photo', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
